version: '3.8'

services:
  app:
    container_name: node_app
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn dev
    expose:
      - ${PORT}
    environment:
      VIRTUAL_HOST: 'node-app.docker'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app

    