import { DataTypes, QueryInterface, Sequelize } from 'sequelize'

const DATA = [
  {
    group: 'Betriebstechnische Anlagen',
    type: 'Absauganlagen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Betriebstechnische Anlagen',
    type: 'Blockheizkraftwerke/Kraftwärmekopplungsanlagen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Betriebstechnische Anlagen',
    type: 'Brand-/Einbruchmeldeanlagen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Betriebstechnische Anlagen',
    type: 'Filteranlagen (Betriebstechnische Anlagen)',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Betriebstechnische Anlagen',
    type: 'Klima-/Kühlanlagen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Betriebstechnische Anlagen',
    type: 'Lüftungsanlagen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Betriebstechnische Anlagen',
    type: 'Notstromanlagen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Betriebstechnische Anlagen',
    type: 'Schaltanlagen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Betriebstechnische Anlagen',
    type: 'Stationäre Stromaggregate/Kompressoren',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Betriebstechnische Anlagen',
    type: 'Transformatoren',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Betriebstechnische Anlagen',
    type: 'Waren-/Lasten/Personenaufzüge',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Grafisches Gewerbe',
    type: '3D-Drucker',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Grafisches Gewerbe',
    type: 'Bindemaschinen',
    machineQuestion: 0,
    allocation: 'Grafisches Gewerbe',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Grafisches Gewerbe',
    type: 'Bogenoffset-/Bogendruckmaschinen',
    machineQuestion: 0,
    allocation: 'Grafisches Gewerbe',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Grafisches Gewerbe',
    type: 'Digitaldruckmaschinen',
    machineQuestion: 0,
    allocation: 'Grafisches Gewerbe',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Grafisches Gewerbe',
    type: 'Druckplattenbelichter',
    machineQuestion: 0,
    allocation: 'Grafisches Gewerbe',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Grafisches Gewerbe',
    type: 'Druckvorstufen',
    machineQuestion: 0,
    allocation: 'Grafisches Gewerbe',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Grafisches Gewerbe',
    type: 'Etikettendruckmaschinen',
    machineQuestion: 0,
    allocation: 'Grafisches Gewerbe',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Grafisches Gewerbe',
    type: 'Falzmaschinen',
    machineQuestion: 0,
    allocation: 'Grafisches Gewerbe',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Grafisches Gewerbe',
    type: 'Flexo-/Siebdruckmaschinen',
    machineQuestion: 0,
    allocation: 'Grafisches Gewerbe',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Grafisches Gewerbe',
    type: 'Foliendruckmaschinen',
    machineQuestion: 0,
    allocation: 'Grafisches Gewerbe',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Grafisches Gewerbe',
    type: 'Foto-/Lichtsatzmaschinen',
    machineQuestion: 0,
    allocation: 'Grafisches Gewerbe',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Grafisches Gewerbe',
    type: 'Hefter',
    machineQuestion: 0,
    allocation: 'Grafisches Gewerbe',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Grafisches Gewerbe',
    type: 'Kreuzleger/Stacker',
    machineQuestion: 0,
    allocation: 'Grafisches Gewerbe',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Grafisches Gewerbe',
    type: 'Kuvertanleger',
    machineQuestion: 0,
    allocation: 'Grafisches Gewerbe',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Grafisches Gewerbe',
    type: 'Kuvertiermaschinen',
    machineQuestion: 0,
    allocation: 'Grafisches Gewerbe',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Grafisches Gewerbe',
    type: 'Lackiermaschinen',
    machineQuestion: 0,
    allocation: 'Grafisches Gewerbe',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Grafisches Gewerbe',
    type: 'Laminatoren',
    machineQuestion: 0,
    allocation: 'Grafisches Gewerbe',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Grafisches Gewerbe',
    type: 'Locher',
    machineQuestion: 0,
    allocation: 'Grafisches Gewerbe',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Grafisches Gewerbe',
    type: 'Papierballenpressen',
    machineQuestion: 0,
    allocation: 'Grafisches Gewerbe',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Grafisches Gewerbe',
    type: 'Perforiermaschinen',
    machineQuestion: 0,
    allocation: 'Grafisches Gewerbe',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Grafisches Gewerbe',
    type: 'Repromaschinen',
    machineQuestion: 0,
    allocation: 'Grafisches Gewerbe',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Grafisches Gewerbe',
    type: 'Rollenoffsetdruckmaschinen',
    machineQuestion: 0,
    allocation: 'Grafisches Gewerbe',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Grafisches Gewerbe',
    type: 'Rotationsdruckmaschinen',
    machineQuestion: 0,
    allocation: 'Grafisches Gewerbe',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Grafisches Gewerbe',
    type: 'Schneidemaschinen (Grafisches Gewerbe)',
    machineQuestion: 0,
    allocation: 'Grafisches Gewerbe',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Grafisches Gewerbe',
    type: 'Schnellpressen',
    machineQuestion: 0,
    allocation: 'Grafisches Gewerbe',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Grafisches Gewerbe',
    type: 'Stanzmaschinen',
    machineQuestion: 0,
    allocation: 'Grafisches Gewerbe',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Grafisches Gewerbe',
    type: 'Tiegeldruckpressen',
    machineQuestion: 0,
    allocation: 'Grafisches Gewerbe',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Grafisches Gewerbe',
    type: 'Zusammentragmaschinen',
    machineQuestion: 0,
    allocation: 'Grafisches Gewerbe',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Grafisches Gewerbe',
    type: 'Zylinderautomaten',
    machineQuestion: 0,
    allocation: 'Grafisches Gewerbe',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Band-/Kreissägen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung b',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Bearbeitungs-/Transferzentren',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung b',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Biegemaschinen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung a',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Bohrwerke/-maschinen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung b',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Drahtziehmaschinen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung b',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Drechselbänke',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung b',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Drehmaschinen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung b',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Drückmaschinen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung a',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Entgratungsmaschine',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung a',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Enthülser',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung b',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Erodiermaschinen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung b',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Extrudermaschinen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung b',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Fas- und Endenbearbeitungsmaschinen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung b',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Fräsen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung b',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Glasschneidemaschinen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung b',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Gravieranlagen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung b',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Hobel-/Kehlmaschinen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung b',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Honmaschinen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung b',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Klink-/Stanzmaschinen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung a',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Knet-/Walzmaschinen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung a',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Lochmaschinen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung a',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Lötautomaten',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung b',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Nibbelmaschinen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung a',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Nietmaschinen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung a',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Oberflächenveredelungsanlagen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung b',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Plattenbearbeitungsmaschinen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung a',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Poliermaschinen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung b',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Pressen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung a',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Rundtaktmaschinen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung b',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Sandstrahlkabinen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung b',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Schälmaschinen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung b',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Scheren und Schermaschinen (Metall-/Stein-/Glas-/Kunststoff- und Holzbe-/verarbeitung)',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung a',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Schleifmaschinen (Metall-/Stein-/Glas-/Kunststoff- und Holzbe-/verarbeitung)',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung b',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Schneideanlagen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung a',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Schweißautomaten/-roboter',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung b',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Schweißmanipulatoren/-tische',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung b',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Sickenmaschinen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung a',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Stationäre Mess- und Prüfmaschinen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung b',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Stemmmaschinen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung a',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Stoßmaschinen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung a',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Trocknungsanlagen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung a',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Verseilmaschinen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung a',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Metall-, Stein-, Glas-, Kunststoff- und Holzbe-/verarbeitung',
    type: 'Wulstmaschinen',
    machineQuestion: 1,
    allocation: null,
    plasticProcessing: 'Chemie, Kunststoff/Gummi und Linoleum',
    metalStoneGlassProcessing:
      'Metallverarbeitung, -bearbeitung und Kaltumformung a',
    woodProcessing: 'Anfragepflichtig',
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Abfüll-/Verpackungsanlagen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Autoklaven (Nahrungs-/Genuss-/Futtermittelindustrie)',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Brecher',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Butter-/Käsefertiger',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Cutter (Nahrungs-/Genuss-/Futtermittelindustrie)',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Destillationsanlagen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Diffusionstürme',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Durchlauf-/Backöfen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Eindampf-/Verdampfanlagen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Entleerungssysteme',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Entschwartungsmaschinen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Etikettiermaschinen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Fermenter',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Filteranlagen (Nahrungs-/Genuss-/Futtermittelindustrie)',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Flaschenreinigungsanlagen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Fleischwölfe',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Frucht-/Käse-/Teigwaren- und Würfelpressen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Gärschränke',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Grastrocknungsanlagen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Homogenisatoren',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Kneter',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Koch-/Brüh-/Dampfkessel',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Kollergänge',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Kühlraumanlagen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Mühlen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Pasteurisierungsanlagen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Pökelinjektoren',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Pumpen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Rauchanlagen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Röster',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Rüben-/Kartoffelwaschanlagen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Rührwerke/Mischanlagen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Schälmaschinen (Nahrungs-/Genuss-/Futtermittelindustrie)',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Schneidemaschinen (Nahrungs-/Genuss-/Futtermittelindustrie)',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Silos/Tanks',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'stationäre Waagen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Teigmischer',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Teigwarenautomaten',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Tiefkühltruhen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Tumbler',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Walzwerke',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Würzepfannen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Nahrungs-, Genuss- und Futtermittelindustrie',
    type: 'Zentrifugen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Sonstige Maschinen',
    type: 'Andere/sonstige Maschine',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Autoklaven (Textilindustrie)',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Ballenöffner',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Bügelmaschinen/-automaten',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Cottonmaschinen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Cutter (Textilindustrie)',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Dämpfmaschinen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Färbe-/Textildruck-/Flockmaschinen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Flechtmaschinen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Haspelmaschinen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Kämmmaschinen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Kardiermaschinen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Kaulen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Kratzenrauhmaschinen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Krempelwölfe',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Malimomaschinen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Nähmaschinen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Nitschelwerke',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Rakel',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Schärmaschinen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Scheren und Schermaschinen (Textilindustrie)',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Schleifmaschinen (Textilindustrie)',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Sengmaschinen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Spannrahmen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Spinn-/Zwirnmaschinen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Spulmaschinen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Stickmaschinen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Strickmaschinen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Trockenmaschinen/-automaten und Waschtrockner',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Tunnelfinisher',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Verpackungsanlagen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Verweilkammern',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Walkmühlen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Waschmaschinen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Webstühle/-maschinen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Textilindustrie',
    type: 'Wirk-/Häkelgalon-/Raschelmaschinen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Transport- und Lagertechnik',
    type: 'Flaschenzüge',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Transport- und Lagertechnik',
    type: 'Förderbänder',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Transport- und Lagertechnik',
    type: 'Hallenlauf-/Portal-/Brückenkrane inklusive Träger und Laufbahnen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Transport- und Lagertechnik',
    type: 'Palettierer',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Transport- und Lagertechnik',
    type: 'Plattengreifer',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Transport- und Lagertechnik',
    type: 'Regalstapelanlagen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Transport- und Lagertechnik',
    type: 'Rohrpostanlagen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Transport- und Lagertechnik',
    type: 'Rollenbahnen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Transport- und Lagertechnik',
    type: 'Sorter',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Transport- und Lagertechnik',
    type: 'Stationäre Hebebühnen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
  {
    group: 'Transport- und Lagertechnik',
    type: 'Wendeeinheiten/-traversen',
    machineQuestion: 0,
    allocation: 'Anfragepflichtig',
    plasticProcessing: null,
    metalStoneGlassProcessing: null,
    woodProcessing: null,
  },
]

export = {
  up: async (queryInterface: QueryInterface) => {
    await queryInterface.createTable('machine_types', {
      id: {
        type: DataTypes.INTEGER.UNSIGNED,
        autoIncrement: true,
        primaryKey: true,
      },
      group: {
        type: new DataTypes.STRING(128),
        allowNull: false,
      },
      type: {
        type: new DataTypes.STRING(128),
        allowNull: false,
      },
      machineQuestion: {
        type: new DataTypes.BOOLEAN(),
        allowNull: false,
      },
      allocation: {
        type: new DataTypes.STRING(128),
        allowNull: true,
      },
      plasticProcessing: {
        type: new DataTypes.STRING(128),
        allowNull: true,
      },
      metalStoneGlassProcessing: {
        type: new DataTypes.STRING(128),
        allowNull: true,
      },
      woodProcessing: {
        type: new DataTypes.STRING(128),
        allowNull: true,
      },
      createdAt: {
        type: new DataTypes.DATE(),
        defaultValue: Sequelize.literal('NOW()'),
        allowNull: false,
      },
      updatedAt: {
        type: new DataTypes.DATE(),
        allowNull: true,
      },
    })
    return queryInterface.bulkInsert('machine_types', DATA)
  },

  down: (queryInterface: QueryInterface) => {
    return queryInterface.dropTable('machine_types')
  },
}
